[connections.postgresql]
dialect = "postgresql"
host = "ce764516-c236-49bf-809e-68c367753e00.supabase.com" # Cambiá esto por el 'Host' exacto que te dé Supabase
user = "cqhygtqelfftdzcnzmie"       # Este es tu usuario (incluye el ID de tu proyecto)
password = "ComparadordePreciosCRDBDanito1024!"       # La contraseña que creaste al fundar el proyecto
database = "postgres"                        # En Supabase por defecto la base de datos se llama 'postgres'
port = 5432
